// Import necessary dependencies
import type { Metadata } from 'next'
import { Inter } from 'next/font/google' // Import Inter CSS for font styling
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

// Initialize Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] })

// Define metadata for the application
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Define the RootLayout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>{children}</body>
    </html>
  </ClerkProvider>
  )
}
